# Scrapping of Used Car from cardekho website

In [1]:
# Importing Libraries

import selenium
import pandas as pd
import numpy as np
from bs4 import BeautifulSoup
from selenium import webdriver
import warnings
warnings.filterwarnings('ignore')
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException
from selenium.webdriver.support.ui import WebDriverWait
import time

In [2]:
# Connecting to Edge webdriver
driver=webdriver.Chrome('chromedrivers.exe')

In [3]:
url = "https://www.cardekho.com/"
driver.get(url)
time.sleep(3)

In [4]:
#link for city
used_cars = driver.find_element_by_xpath("/html/body/div[2]/div/header/div[2]/div/div/nav/ul/li[2]/ul/li[2]/a")

In [5]:
used_cars

In [6]:
used_cars = used_cars.get_attribute('href')

In [7]:
used_cars

'https://www.cardekho.com/used-cars+in+bangalore#'

In [8]:
driver.get(used_cars)
time.sleep(3)

In [16]:
name=[]
price=[]
running_km=[]
fuel_type=[]
transmission=[]
for _ in range(150):
        time.sleep(1)
        driver.execute_script("window.scrollBy(0,1000)")
        # Scraping the Car Name
        for i in driver.find_elements_by_xpath("//div[@class='gsc_col-xs-7  carsName']/a"):
            name.append(i.text)
        # Scraping the Car Price value
        for i in driver.find_elements_by_xpath("//div[@class=' price']/span[2]"):
            price.append(i.text)
        # Scraping the Kilometer data    
        for i in driver.find_elements_by_xpath("//div[@class='truncate dotlist-2']/div[1]"):
            running_km.append(i.text)
        # Scraping the Fuel Type    
        for i in driver.find_elements_by_xpath("//div[@class='truncate dotlist-2']/div[2]"):
            fuel_type.append(i.text)
        # Scraping the Gear Transmission data    
        for i in driver.find_elements_by_xpath("//div[@class='truncate dotlist-2']/div[3]"):
            transmission.append(i.text)

In [75]:
# Scrapping the car url
car_url=[]
for _ in range(110):
        time.sleep(1)
        driver.execute_script("window.scrollBy(0,1000)")
        current_url = driver.current_url    
        car = driver.find_elements_by_xpath("//div[@class='gsc_col-xs-7  carsName']/a")
        for i in car:
            car_url.append(i.get_attribute('href'))

In [ ]:
milleage=[]
color=[]
max_power=[]
engine=[]
seat=[]
front_brake=[]
length=[]
width=[]
height=[]
weight=[]
wheel_base=[]
front_tread=[]
rear_tread=[]
engine_type=[]

for i in car_url:
    driver.get(i)
    time.sleep(3)
    # Scraping the Car Milleage Data
    try:
        view_more = driver.find_element_by_xpath("//*[text() = 'View All Specifications' or text() = 'View More']")
        driver.execute_script("arguments[0].scrollIntoView();", view_more)
        driver.execute_script("arguments[0].click();", view_more)
        time.sleep(2)
    except NoSuchElementException:
        pass
    
    #Scraping the Milleage data
    try:
        for i in driver.find_elements_by_xpath("//*[text()='Mileage']/following-sibling::div"):
            milleage.append(i.text.replace('kmpl',''))
    except NoSuchElementException:
        milleage.append('-')
        
    #Scraping the color:
    try:
        for i in driver.find_elements_by_xpath("//*[text()='Color']/following-sibling::div"):
            color.append(i.text)
    except NoSuchElementException:
        color.append('-')
        
    #Scraping the Max Power:
    try:
        for i in driver.find_elements_by_xpath("//*[text()='Max Power']/following-sibling::div"):
            max_power.append(i.text)
    except NoSuchElementException:
        max_power.append('-')
        
    #Scraping the Engine
    try:
        for i in driver.find_elements_by_xpath("//*[text()='Engine']/following-sibling::div"):
            engine.append(i.text)
    except NoSuchElementException:
        engine.append('-')
        
    #Scraping the Seat
    try:
        for i in driver.find_elements_by_xpath("//*[text()='Seats']/following-sibling::div"):
            seat.append(i.text)
    except NoSuchElementException:
        seat.append('-')
    
    #Scraping the Front Brake:
    try:
        for i in driver.find_elements_by_xpath("//*[text()='Front Brake Type']/following-sibling::div"):
            front_brake.append(i.text)
    except NoSuchElementException:
        front_brake.append('-')
    
    #Scraping the Length
    try:
        for i in driver.find_elements_by_xpath("//*[text()='Length']/following-sibling::div"):
            length.append(i.text.replace('mm',''))
    except NoSuchElementException:
        length.append('-')
        
    #Scraping the Width:
    try:
        for i in driver.find_elements_by_xpath("//*[text()='Width']/following-sibling::div"):
            width.append(i.text.replace('mm',''))
    except NoSuchElementException:
        width.append('-')
        
    #Scraping the Height:
    try:
        for i in driver.find_elements_by_xpath("//*[text()='Height']/following-sibling::div"):
            height.append(i.text.replace('mm',''))
    except NoSuchElementException:
        height.append('-')
        
    #Scraping the Kerb Weight:
    try:
        for i in driver.find_elements_by_xpath("//*[text()='Kerb Weight']/following-sibling::div"):
            weight.append(i.text.replace('kg',''))
    except NoSuchElementException:
        weight.append('-')
        
    #Scraping the Wheel Base
    try:
        for i in driver.find_elements_by_xpath("//*[text()='Wheel Base']/following-sibling::div"):
            wheel_base.append(i.text.replace('mm',''))
    except NoSuchElementException:
        wheel_base.append('-')
        
    #Scraping the Front Tread
    try:
        for i in driver.find_elements_by_xpath("//*[text()='Front Tread']/following-sibling::div"):
            front_tread.append(i.text.replace('mm',''))
    except NoSuchElementException:
        front_tread.append('-')
        
    #Scraping the Rear Tread
    try:
        for i in driver.find_elements_by_xpath("//*[text()='Rear Tread']/following-sibling::div"):
            rear_tread.append(i.text.replace('mm',''))
    except NoSuchElementException:
        rear_tread.append('-')
        
    #Scraping the Engine Type
    try:
        for i in driver.find_elements_by_xpath("//*[text()='Engine Type']/following-sibling::div"):
            engine_type.append(i.text)
    except NoSuchElementException:
        engine_type.append('-')

In [18]:
len(running_km),len(name),len(price),len(fuel_type),len(transmission)

(17780, 17660, 17740, 17780, 17780)

In [76]:
len(car_url)

6340

In [97]:
len(milleage)

3693

In [104]:
df=pd.DataFrame()
df['Milleage']=milleage[:3693]
df['Max_Power']=max_power[:3693]
df['Engine']=engine[:6000]
df['Seat']=seat[:6000]
df['Color']=color[:6000]
df['Front Brake']=front_brake[:6000]
df['Engine_Type']=engine_type[:6000]
df['Length']=length[:6000]
df['Width']=width[:6000]
df['Height']=height[:6000]
df['Wheel_Base']=wheel_base[:6000]
df

,Milleage,Max_Power,Engine,Seat,Color,Front Brake,Engine_Type,Length,Width,Height,Wheel_Base
0,20.73,91.1bhp,1373 CC,5,Grey,Ventilated Disc,k14B VVT Engine,4490,1730,1485,2650
1,21.21,91.1bhp@6000rpm,1197 CC,5,Oxford Blue,Disc,K Series VVT Engine,3995,1735,1515,2450
2,21.1,81.80bhp,998 CC,5,Fire Red,Disc,Boosterjet Petrol Engine,3995,1745,1510,2520
3,20.65,81.80bhp@6000rpm,1462 CC,5,Nexa Blue,Ventilated Disc,K15 Smart Hybrid Petrol Engine,4490,1730,1485,2650
4,21.01,100.5bhp,1197 CC,5,Blue,Disc,1.2L VVT Engine,3995,1745,1510,2520
...,...,...,...,...,...,...,...,...,...,...,...
3688,18.9,81.80bhp,1197 CC,5,Blue,Disc,Kappa VTVT Petrol Engine,3765,1660,1520,2425
3689,17.4,81.80bhp@6000rpm,1497 CC,5,Red,Ventilated Disc,i VTEC Engine,4440,1695,1495,2600
3690,23.95,83.1bhp,998 CC,5,Orange,Ventilated Disc,K Series Petrol Engine,3545,1515,1475,2360
3691,17.21,83.1bhp@6000rpm,1197 CC,5,Red,Disc,TSI Petrol Engine,3971,1682,1469,2469
3692,23.84,117.6bhp,1199 CC,5,Red,Disc,Revotron Engine,3746,1647,1535,2400

In [98]:
df.to_csv("car_price_specification.csv")

In [19]:
df=pd.DataFrame()
df['Car_Name']=name[:6000]
df['Running_kms']=running_km[:6000]
df['Fuel_Type']=fuel_type[:6000]
df['Gear Transmission']=transmission[:6000]
df['Price']=price[:6000]
df

,Car_Name,Running_kms,Fuel_Type,Gear Transmission,Price
0,2014 Hyundai Xcent,"43,701 kms",Petrol,Manual,4.70 Lakh
1,2014 Hyundai Grand i10,"43,980 kms",Petrol,Manual,4.33 Lakh
2,2014 Honda Brio,"21,420 kms",Petrol,Manual,4.20 Lakh
3,2021 Maruti Swift Dzire,752 kms,Petrol,Manual,7.90 Lakh
4,2018 Toyota Yaris,"7,599 kms",Petrol,Manual,9.46 Lakh
...,...,...,...,...,...
5995,2012 Honda City,"74,252 kms",Petrol,Manual,4.15 Lakh
5996,2018 Renault Duster,"35,802 kms",Petrol,Automatic,5.45 Lakh
5997,2019 Maruti Celerio,"10,000 kms",Petrol,Automatic,6.66 Lakh
5998,2018 Maruti Swift Dzire,"74,253 kms",Petrol,Manual,5.40 Lakh
5999,2019 Hyundai Venue,"10,222 kms",Petrol,Automatic,6.26 Lakh

In [20]:
df.to_csv('used_car_price.csv')